/**
 * The naked-eye comets, one entry per apparition.
 *
 * GENERATED by scripts/build-comet-catalog.ts — edit that script, not this file. The orbits come
 * from JPL Horizons, asked for osculating elements at each apparition's own perihelion; the peak
 * magnitudes are recorded observations entered by hand there, and every other photometric number
 * here is derived from them. See the script's own doc comment for why the two are kept apart.
 */
import type { OrbitalElements } from "./Orbit.js"

export interface CometApparition {
  /** Stable id, what a case file would name. */
  id: string
  /** The IAU designation. Two apparitions of the same comet share it and differ by `id`. */
  designation: string
  /** The comet's name in each language a page can be read in — the same "translate the label, keep
   * the identifier" rule the meteor showers and the decor kinds follow. Most comets are named after
   * whoever found them and read the same in both; the descriptive ones do not. */
  name: { en: string; fr: string }
  orbit: OrbitalElements
  /** The brightest visual magnitude on record for this apparition, and the date it was recorded.
   * An OBSERVATION — everything else about the brightness is worked out from it. */
  peakMagnitude: number
  peakOn: string
  /** A second recorded magnitude and its date, where one was needed to pin the activity exponent
   * down — see the build script. Absent for every apparition whose exponent is the assumed one. */
  alsoRecordedMagnitude?: number
  alsoRecordedOn?: string
  /** What the light curve has to be anchored at, and how steeply it has to fall, to reproduce the
   * recorded magnitudes above. Model parameters, not measurements: see Comets.magnitudeAt. */
  absoluteMagnitude: number
  activityExponent: number
  /** The greatest tail length on record, in degrees of sky, and the physical length in astronomical
   * units that subtends it from where the Earth stood that night. Both absent when no figure is on
   * record, and an apparition without one is drawn with no tail at all rather than a guessed one. */
  tailLengthDeg?: number
  tailLengthAu?: number
  /** What is worth knowing about this apparition, in the terms a case file would want. */
  note?: string
}

export const BRIGHT_COMETS: CometApparition[] = [
  {
    id: "halley-1910",
    designation: "1P/Halley",
    name: { en: "Halley's Comet", fr: "comète de Halley" },
    orbit: {
      eccentricity: 0.9672960498922706,
      perihelionAu: 0.5872100477652511,
      inclinationDeg: 162.218798367122,
      ascendingNodeDeg: 58.56208298700436,
      argumentOfPerihelionDeg: 111.7366940639061,
      perihelionJd: 2418781.6784171113
    },
    peakMagnitude: 0,
    peakOn: "1910-05-20",
    absoluteMagnitude: 4.72,
    activityExponent: 4,
    tailLengthDeg: 100,
    tailLengthAu: 0.1638,
    note: "Passed 0.15 au from Earth on 20 May 1910, and the Earth crossed the outer tail the day before — the apparition that produced a genuine public panic."
  },
  {
    id: "brooks-1911",
    designation: "C/1911 O1",
    name: { en: "Comet Brooks", fr: "comète Brooks" },
    orbit: {
      eccentricity: 0.9876404970138669,
      perihelionAu: 0.4898172916113738,
      inclinationDeg: 33.34043866978714,
      ascendingNodeDeg: 293.7022074981857,
      argumentOfPerihelionDeg: 153.5578007321686,
      perihelionJd: 2419337.8856140426
    },
    peakMagnitude: 2,
    peakOn: "1911-10-25",
    absoluteMagnitude: 5.59,
    activityExponent: 4,
  },
  {
    id: "skjellerup-maristany-1927",
    designation: "C/1927 X1",
    name: { en: "Comet Skjellerup-Maristany", fr: "comète Skjellerup-Maristany" },
    orbit: {
      eccentricity: 0.999839726885059,
      perihelionAu: 0.1761569619628186,
      inclinationDeg: 85.1125991950808,
      ascendingNodeDeg: 78.24360172472711,
      argumentOfPerihelionDeg: 47.15877857390136,
      perihelionJd: 2425232.6808989984
    },
    peakMagnitude: -6,
    peakOn: "1927-12-15",
    absoluteMagnitude: 1.19,
    activityExponent: 4,
    note: "One of the few comets of the century seen in full daylight."
  },
  {
    id: "de-kock-paraskevopoulos-1941",
    designation: "C/1941 B2",
    name: { en: "Comet de Kock-Paraskevopoulos", fr: "comète de Kock-Paraskevopoulos" },
    orbit: {
      eccentricity: 0.9991026715181549,
      perihelionAu: 0.7900329662827822,
      inclinationDeg: 168.2039226531089,
      ascendingNodeDeg: 43.10609347214336,
      argumentOfPerihelionDeg: 268.6990344196369,
      perihelionJd: 2430022.157765061
    },
    peakMagnitude: 2,
    peakOn: "1941-02-05",
    absoluteMagnitude: 5.01,
    activityExponent: 4,
  },
  {
    id: "southern-1947",
    designation: "C/1947 X1",
    name: { en: "the Southern Comet", fr: "comète australe" },
    orbit: {
      eccentricity: 0.9998424430916737,
      perihelionAu: 0.1100045955093761,
      inclinationDeg: 138.5113919632757,
      ascendingNodeDeg: 337.3114969669252,
      argumentOfPerihelionDeg: 196.1820121395961,
      perihelionJd: 2432522.0864727003
    },
    peakMagnitude: -3,
    peakOn: "1947-12-08",
    absoluteMagnitude: 3.01,
    activityExponent: 4,
    note: "A bright southern-hemisphere comet of December 1947, the month the American sighting wave of that year was still being argued over."
  },
  {
    id: "eclipse-1948",
    designation: "C/1948 V1",
    name: { en: "the Eclipse Comet", fr: "comète de l'éclipse" },
    orbit: {
      eccentricity: 0.9999130678247334,
      perihelionAu: 0.1354437057263306,
      inclinationDeg: 23.11668597152911,
      ascendingNodeDeg: 211.0454985994762,
      argumentOfPerihelionDeg: 107.2474157073104,
      perihelionJd: 2432851.9265329437
    },
    peakMagnitude: -2,
    peakOn: "1948-11-01",
    absoluteMagnitude: 4.79,
    activityExponent: 4,
    note: "Found during the total solar eclipse of 1 November 1948, which is how a comet that bright had gone unnoticed: it had been hidden in the Sun's glare."
  },
  {
    id: "arend-roland-1957",
    designation: "C/1956 R1",
    name: { en: "Comet Arend-Roland", fr: "comète Arend-Roland" },
    orbit: {
      eccentricity: 1.0002570255357,
      perihelionAu: 0.3160532361485914,
      inclinationDeg: 119.9440863251822,
      ascendingNodeDeg: 215.8548157717755,
      argumentOfPerihelionDeg: 308.775920364167,
      perihelionJd: 2435936.5327396123
    },
    peakMagnitude: 0.5,
    peakOn: "1957-04-25",
    absoluteMagnitude: 3.96,
    activityExponent: 4,
    note: "Showed a spike pointing back TOWARD the Sun in late April 1957 — a real anti-tail, and much reported at the time."
  },
  {
    id: "mrkos-1957",
    designation: "C/1957 P1",
    name: { en: "Comet Mrkos", fr: "comète Mrkos" },
    orbit: {
      eccentricity: 0.9993521583504134,
      perihelionAu: 0.3549238508212375,
      inclinationDeg: 93.9433042053929,
      ascendingNodeDeg: 68.32441518619923,
      argumentOfPerihelionDeg: 40.31823675802871,
      perihelionJd: 2436051.93752228
    },
    peakMagnitude: 1,
    peakOn: "1957-08-05",
    absoluteMagnitude: 5.07,
    activityExponent: 4,
    note: "The second bright naked-eye comet of 1957, four months after Arend-Roland."
  },
  {
    id: "seki-lines-1962",
    designation: "C/1962 C1",
    name: { en: "Comet Seki-Lines", fr: "comète Seki-Lines" },
    orbit: {
      eccentricity: 1.000003791331562,
      perihelionAu: 0.03139689112215131,
      inclinationDeg: 65.01487186102287,
      ascendingNodeDeg: 304.6776602796538,
      argumentOfPerihelionDeg: 11.47295326312573,
      perihelionJd: 2437756.163010178
    },
    peakMagnitude: -2.5,
    peakOn: "1962-04-01",
    absoluteMagnitude: 9.3,
    activityExponent: 4,
  },
  {
    id: "ikeya-seki-1965",
    designation: "C/1965 S1",
    name: { en: "Comet Ikeya-Seki", fr: "comète Ikeya-Seki" },
    orbit: {
      eccentricity: 0.9999141178248997,
      perihelionAu: 0.007785966366889336,
      inclinationDeg: 141.8642315267051,
      ascendingNodeDeg: 346.9951764632611,
      argumentOfPerihelionDeg: 69.04909813996062,
      perihelionJd: 2439054.6837018197
    },
    peakMagnitude: -10,
    peakOn: "1965-10-21",
    alsoRecordedMagnitude: 2,
    alsoRecordedOn: "1965-10-30",
    absoluteMagnitude: 5.26,
    activityExponent: 4.002,
    tailLengthDeg: 25,
    tailLengthAu: 0.5048,
    note: "A sungrazer that passed 450 000 km above the Sun's surface and was seen beside it in broad daylight — the brightest comet of the twentieth century. It then stood in the dawn sky for a fortnight with a tail some 25 degrees long, which is the second magnitude recorded here."
  },
  {
    id: "bennett-1970",
    designation: "C/1969 Y1",
    name: { en: "Comet Bennett", fr: "comète Bennett" },
    orbit: {
      eccentricity: 0.9962979048768408,
      perihelionAu: 0.5376209981502136,
      inclinationDeg: 90.03975717147327,
      ascendingNodeDeg: 224.6576652531314,
      argumentOfPerihelionDeg: 354.1494209173161,
      perihelionJd: 2440665.5455270996
    },
    peakMagnitude: 0,
    peakOn: "1970-03-26",
    absoluteMagnitude: 3.36,
    activityExponent: 4,
  },
  {
    id: "white-ortiz-bolelli-1970",
    designation: "C/1970 K1",
    name: { en: "Comet White-Ortiz-Bolelli", fr: "comète White-Ortiz-Bolelli" },
    orbit: {
      eccentricity: 0.9999488875801225,
      perihelionAu: 0.00884411465256722,
      inclinationDeg: 138.9520738221631,
      ascendingNodeDeg: 336.8194095816687,
      argumentOfPerihelionDeg: 61.10224765396615,
      perihelionJd: 2440720.9807728203
    },
    peakMagnitude: 1,
    peakOn: "1970-05-22",
    absoluteMagnitude: 4.35,
    activityExponent: 4,
  },
  {
    id: "kohoutek-1973",
    designation: "C/1973 E1",
    name: { en: "Comet Kohoutek", fr: "comète Kohoutek" },
    orbit: {
      eccentricity: 1.000007152175185,
      perihelionAu: 0.1424250377812859,
      inclinationDeg: 14.30414984159355,
      ascendingNodeDeg: 258.4893339663974,
      argumentOfPerihelionDeg: 37.79772760699667,
      perihelionJd: 2442044.930687027
    },
    peakMagnitude: 0,
    peakOn: "1974-01-05",
    absoluteMagnitude: 4.89,
    activityExponent: 4,
    note: "Announced in advance as the comet of the century and remembered for disappointing: it was an ordinary naked-eye object, not the spectacle the press had promised."
  },
  {
    id: "west-1976",
    designation: "C/1975 V1",
    name: { en: "Comet West", fr: "comète West" },
    orbit: {
      eccentricity: 1.000017859625611,
      perihelionAu: 0.1966006188461085,
      inclinationDeg: 43.07319920579427,
      ascendingNodeDeg: 118.9189245655447,
      argumentOfPerihelionDeg: 358.4315101259072,
      perihelionJd: 2442833.721841768
    },
    peakMagnitude: -3,
    peakOn: "1976-02-25",
    absoluteMagnitude: 4.41,
    activityExponent: 4,
    tailLengthDeg: 30,
    tailLengthAu: 0.4325,
    note: "Broke into four pieces at perihelion. Barely reported at the time — the press had been burned by Kohoutek two years earlier."
  },
  {
    id: "iras-araki-alcock-1983",
    designation: "C/1983 H1",
    name: { en: "Comet IRAS-Araki-Alcock", fr: "comète IRAS-Araki-Alcock" },
    orbit: {
      eccentricity: 0.9898409731606003,
      perihelionAu: 0.9913412593828502,
      inclinationDeg: 73.25000846947029,
      ascendingNodeDeg: 49.10235754476374,
      argumentOfPerihelionDeg: 192.8506176754439,
      perihelionJd: 2445475.7545235856
    },
    peakMagnitude: 1.7,
    peakOn: "1983-05-11",
    absoluteMagnitude: 9.04,
    activityExponent: 4,
    note: "Passed 0.031 au from Earth on 11 May 1983, one of the closest cometary approaches on record: it crossed a quarter of the sky in a night, which no other comet in this list did."
  },
  {
    id: "halley-1986",
    designation: "1P/Halley",
    name: { en: "Halley's Comet", fr: "comète de Halley" },
    orbit: {
      eccentricity: 0.9672792271749998,
      perihelionAu: 0.5871034488173393,
      inclinationDeg: 162.2422242700916,
      ascendingNodeDeg: 58.85993640671803,
      argumentOfPerihelionDeg: 111.8655480539208,
      perihelionJd: 2446470.9589610207
    },
    peakMagnitude: 2.1,
    peakOn: "1986-03-10",
    absoluteMagnitude: 2.71,
    activityExponent: 4,
    note: "The worst-placed return in two thousand years — famous, expected, and for most observers a faint smudge."
  },
  {
    id: "hyakutake-1996",
    designation: "C/1996 B2",
    name: { en: "Comet Hyakutake", fr: "comète Hyakutake" },
    orbit: {
      eccentricity: 0.9997295133739305,
      perihelionAu: 0.2302272039470452,
      inclinationDeg: 124.923592343765,
      ascendingNodeDeg: 188.0454295899424,
      argumentOfPerihelionDeg: 130.1724036582639,
      perihelionJd: 2450204.8946148166
    },
    peakMagnitude: 0,
    peakOn: "1996-03-25",
    absoluteMagnitude: 4.75,
    activityExponent: 4,
    tailLengthDeg: 80,
    tailLengthAu: 1,
    note: "Passed 0.10 au from Earth in March 1996, five weeks BEFORE perihelion, with a tail measured at some 80 degrees — the longest of the modern era."
  },
  {
    id: "hale-bopp-1997",
    designation: "C/1995 O1",
    name: { en: "Comet Hale-Bopp", fr: "comète Hale-Bopp" },
    orbit: {
      eccentricity: 0.9951314746156615,
      perihelionAu: 0.9141695067003724,
      inclinationDeg: 89.43017155012492,
      ascendingNodeDeg: 282.470602866853,
      argumentOfPerihelionDeg: 130.5872524854533,
      perihelionJd: 2450539.633099368
    },
    peakMagnitude: -0.8,
    peakOn: "1997-04-01",
    absoluteMagnitude: -1.06,
    activityExponent: 4,
    tailLengthDeg: 20,
    tailLengthAu: 0.9938,
    note: "Visible to the naked eye for about eighteen months, longer than any comet on record."
  },
  {
    id: "mcnaught-2007",
    designation: "C/2006 P1",
    name: { en: "Comet McNaught", fr: "comète McNaught" },
    orbit: {
      eccentricity: 1.00001811603225,
      perihelionAu: 0.1707325614080681,
      inclinationDeg: 77.83726446452654,
      ascendingNodeDeg: 267.4149080498975,
      argumentOfPerihelionDeg: 155.9756130642756,
      perihelionJd: 2454113.298753579
    },
    peakMagnitude: -5.5,
    peakOn: "2007-01-13",
    absoluteMagnitude: 2.53,
    activityExponent: 4,
    tailLengthDeg: 35,
    tailLengthAu: 0.5009,
    note: "The brightest comet since Ikeya-Seki, seen in daylight beside the Sun in January 2007."
  },
  {
    id: "lovejoy-2011",
    designation: "C/2011 W3",
    name: { en: "Comet Lovejoy", fr: "comète Lovejoy" },
    orbit: {
      eccentricity: 0.999915056276912,
      perihelionAu: 0.005553783989325053,
      inclinationDeg: 134.3558712062691,
      ascendingNodeDeg: 326.3693517957772,
      argumentOfPerihelionDeg: 53.50991655176601,
      perihelionJd: 2455911.511809431
    },
    peakMagnitude: -3,
    peakOn: "2011-12-16",
    alsoRecordedMagnitude: 1.5,
    alsoRecordedOn: "2011-12-22",
    absoluteMagnitude: 3.51,
    activityExponent: 1.194,
    note: "A sungrazer that was expected to be destroyed at perihelion and came out the other side, to stand in the southern dawn sky for the rest of December — which is the second magnitude recorded here."
  },
  {
    id: "panstarrs-2013",
    designation: "C/2011 L4",
    name: { en: "Comet PANSTARRS", fr: "comète PANSTARRS" },
    orbit: {
      eccentricity: 1.000032542889696,
      perihelionAu: 0.301544229714915,
      inclinationDeg: 84.2081978367921,
      ascendingNodeDeg: 65.66588626213694,
      argumentOfPerihelionDeg: 333.6516444379993,
      perihelionJd: 2456361.669960698
    },
    peakMagnitude: 1,
    peakOn: "2013-03-10",
    absoluteMagnitude: 5.98,
    activityExponent: 4,
  },
  {
    id: "neowise-2020",
    designation: "C/2020 F3",
    name: { en: "Comet NEOWISE", fr: "comète NEOWISE" },
    orbit: {
      eccentricity: 0.9991782081129224,
      perihelionAu: 0.2946512466331692,
      inclinationDeg: 128.9375043020912,
      ascendingNodeDeg: 61.01042991771634,
      argumentOfPerihelionDeg: 37.2786526292898,
      perihelionJd: 2459034.1788972816
    },
    peakMagnitude: 0.9,
    peakOn: "2020-07-08",
    absoluteMagnitude: 5.79,
    activityExponent: 4,
    tailLengthDeg: 10,
    tailLengthAu: 0.1808,
    note: "The first comet since Hale-Bopp that ordinary observers in the northern hemisphere saw without being told where to look."
  },
  {
    id: "tsuchinshan-atlas-2024",
    designation: "C/2023 A3",
    name: { en: "Comet Tsuchinshan-ATLAS", fr: "comète Tsuchinshan-ATLAS" },
    orbit: {
      eccentricity: 1.000020192843226,
      perihelionAu: 0.3914228969475176,
      inclinationDeg: 139.1105462619479,
      ascendingNodeDeg: 21.55945689078845,
      argumentOfPerihelionDeg: 308.4913086299446,
      perihelionJd: 2460581.242087108
    },
    peakMagnitude: 0,
    peakOn: "2024-10-14",
    absoluteMagnitude: 3.97,
    activityExponent: 4,
    tailLengthDeg: 20,
    tailLengthAu: 0.1902,
    note: "Briefly reported far brighter around 9 October 2024, when it stood almost between the observer and the Sun and forward-scattered the light through its own dust — a geometry this catalog's brightness model does not attempt, so what is stored is the ordinary evening-sky peak a few days later."
  }
]
