/**
 * What was in orbit, month by month, and the classes of it worth naming.
 *
 * GENERATED by scripts/build-satellite-catalog.ts from CelesTrak's SATCAT
 * (https://celestrak.org/pub/satcat.csv, CC BY 4.0) — edit that script, not this file.
 *
 * Every date here is derived from the catalogue's own launch and decay dates. The SATCAT's orbital
 * fields are deliberately NOT used: they hold each object's CURRENT state, which for anything that
 * has re-entered is its state on the way down (Echo 1 is listed at 419 x 394 km, and spent its life
 * near 1500). See the script's own doc comment.
 */

export interface SatelliteClass {
  id: string
  /** The class's name in each language a page can be read in. */
  name: { en: string; fr: string }
  /** From the first launch of the class, to when it ended — absent while it is still up there. */
  from: string
  to?: string
  /**
   * The brightest this class is recorded as getting, apparent visual magnitude.
   *
   * Here because being SUNLIT and being SEEABLE are two different questions, and only the first is
   * geometry. An Iridium flare at magnitude -8 outshines a daylit sky; an ordinary satellite at
   * magnitude 2 needs a dark one.
   */
  peakMagnitude: number
  /** What made this class worth naming, in the terms a report of the period would have used. */
  note: string
}

export const SATELLITE_CLASSES: SatelliteClass[] = [
  {
    id: "echo",
    name: { en: "the Echo balloons", fr: "les ballons Echo" },
    from: "1960-08-12",
    to: "1969-06-07",
    peakMagnitude: -1,
    note: "Echo 1 and 2 were 30- and 40-metre reflective balloons, as bright as the brightest stars and moving slowly enough to be watched — deliberately visible, widely announced in newspapers, and the first objects most people ever saw crossing the night sky. They fall squarely inside the sighting waves this project reconstructs."
  },
  {
    id: "iridium-flares",
    name: { en: "the Iridium flares", fr: "les flashes d'Iridium" },
    from: "1997-05-05",
    to: "2019-12-27",
    peakMagnitude: -8,
    note: "The original Iridium satellites carried flat, mirror-finish antennas that threw a sunbeam a few kilometres wide across the ground: a still point of sky flaring to magnitude -8 over five seconds and vanishing again. Nothing else in the sky does that."
  },
  {
    id: "iss",
    name: { en: "the International Space Station", fr: "la Station spatiale internationale" },
    from: "1998-11-20",
    peakMagnitude: -5.9,
    note: "Since its first module, and much brighter as it grew: at its best it outshines everything in the sky but the Sun and the Moon, crossing in a straight silent line in about four minutes."
  },
  {
    id: "starlink-trains",
    name: { en: "the Starlink trains", fr: "les trains de Starlink" },
    from: "2019-05-24",
    peakMagnitude: 1,
    note: "In the days after a launch, satellites still bunched in their deployment string cross as an evenly spaced line of lights — the most reported 'formation of UFOs' of the era. They spread out within weeks, so a train is a fact about the days after a launch rather than about the year."
  }
]

/** The month the table below starts at, as year * 12 + (month - 1). */
export const FIRST_TRACKED_MONTH = 23493

/**
 * How many tracked objects — payloads and spent rocket bodies, never debris — were in orbit in each
 * month from the first launch onwards.
 *
 * The one number about satellites with complete historical coverage, and it carries more than it
 * looks: two the month Sputnik went up, a hundred and sixty-one the month of the Socorro landing,
 * two hundred and eighty-one for Valensole, and tens of thousands now. What a witness in 1964 could
 * possibly have mistaken for something else is a different sky from the one overhead today.
 */
export const TRACKED_OBJECTS_BY_MONTH: number[] = [
  2, 3, 2, 1, 2, 5, 4, 6, 5, 6, 6, 6, 6, 6, 6, 6, 9, 9, 9, 9, 9, 9, 14, 14,
  15, 16, 16, 16, 16, 16, 18, 22, 25, 24, 29, 28, 29, 33, 34, 35, 40, 40, 42, 42, 43, 46, 48, 48,
  49, 53, 53, 54, 58, 61, 70, 70, 74, 78, 79, 83, 92, 92, 99, 97, 101, 102, 109, 115, 126, 125, 123, 125,
  127, 130, 139, 153, 157, 156, 161, 156, 165, 174, 193, 193, 201, 203, 212, 215, 224, 244, 255, 263, 262, 281, 293, 307,
  312, 327, 339, 336, 343, 353, 359, 369, 386, 396, 405, 410, 421, 419, 424, 434, 443, 450, 460, 480, 492, 504, 509, 516,
  519, 524, 527, 530, 527, 535, 543, 549, 564, 571, 573, 576, 582, 584, 600, 600, 608, 618, 625, 632, 637, 642, 648, 654,
  661, 667, 669, 667, 671, 671, 697, 692, 703, 697, 710, 714, 724, 731, 747, 755, 764, 770, 782, 802, 801, 815, 819, 837,
  846, 856, 878, 881, 877, 900, 906, 907, 917, 932, 932, 936, 954, 973, 989, 986, 991, 990, 1002, 1009, 1021, 1024, 1040, 1038,
  1058, 1078, 1098, 1092, 1094, 1099, 1122, 1132, 1140, 1151, 1154, 1161, 1176, 1185, 1202, 1206, 1227, 1228, 1243, 1265, 1281, 1288, 1296, 1325,
  1328, 1336, 1354, 1373, 1375, 1393, 1398, 1411, 1432, 1457, 1462, 1476, 1487, 1485, 1506, 1509, 1521, 1524, 1537, 1543, 1563, 1586, 1598, 1614,
  1621, 1620, 1640, 1658, 1660, 1673, 1670, 1686, 1708, 1715, 1726, 1726, 1745, 1749, 1767, 1774, 1790, 1798, 1803, 1805, 1815, 1818, 1819, 1820,
  1833, 1822, 1821, 1819, 1838, 1835, 1845, 1841, 1851, 1869, 1865, 1868, 1871, 1870, 1879, 1882, 1886, 1900, 1899, 1908, 1921, 1928, 1954, 1966,
  1976, 1986, 1999, 2007, 2015, 2030, 2036, 2057, 2067, 2072, 2077, 2088, 2101, 2106, 2112, 2119, 2127, 2142, 2171, 2176, 2203, 2226, 2242, 2241,
  2244, 2254, 2263, 2284, 2300, 2320, 2327, 2345, 2364, 2367, 2402, 2423, 2425, 2434, 2443, 2461, 2476, 2495, 2505, 2520, 2531, 2535, 2556, 2567,
  2599, 2608, 2625, 2639, 2660, 2663, 2668, 2681, 2695, 2702, 2709, 2719, 2720, 2738, 2746, 2763, 2778, 2788, 2796, 2807, 2822, 2831, 2831, 2853,
  2863, 2866, 2883, 2892, 2895, 2921, 2919, 2937, 2941, 2947, 2964, 2987, 2992, 2987, 2995, 3002, 3021, 3025, 3026, 3036, 3052, 3049, 3059, 3077,
  3075, 3083, 3086, 3107, 3123, 3124, 3146, 3155, 3168, 3179, 3204, 3205, 3211, 3233, 3252, 3253, 3276, 3287, 3294, 3293, 3297, 3314, 3326, 3335,
  3338, 3355, 3362, 3358, 3365, 3364, 3376, 3375, 3382, 3418, 3429, 3432, 3455, 3463, 3483, 3490, 3502, 3509, 3521, 3532, 3542, 3544, 3553, 3571,
  3580, 3588, 3596, 3603, 3633, 3639, 3649, 3655, 3660, 3670, 3699, 3699, 3707, 3723, 3747, 3752, 3754, 3766, 3772, 3778, 3781, 3798, 3815, 3814,
  3824, 3832, 3853, 3859, 3879, 3885, 3899, 3912, 3910, 3924, 3937, 3951, 3951, 3961, 3963, 3961, 3976, 3977, 3988, 4004, 4018, 4025, 4047, 4074,
  4086, 4108, 4133, 4136, 4159, 4168, 4182, 4192, 4200, 4215, 4230, 4239, 4257, 4678, 4698, 4694, 4713, 4719, 4739, 4750, 4756, 4764, 4771, 4788,
  4792, 4790, 4809, 4821, 4829, 4834, 4836, 4843, 4853, 4863, 4872, 4881, 4890, 4898, 4901, 4897, 4895, 4884, 4886, 4886, 4894, 4897, 4905, 4905,
  4909, 4907, 4925, 4918, 4920, 4929, 4925, 4928, 4936, 4943, 4944, 4951, 4955, 4952, 4974, 4976, 4975, 4981, 4994, 4997, 5022, 5023, 5032, 5043,
  5048, 5051, 5066, 5062, 5068, 5075, 5082, 5082, 5098, 5102, 5110, 5113, 5119, 5123, 5138, 5138, 5145, 5149, 5157, 5165, 5166, 5169, 5178, 5183,
  5190, 5192, 5203, 5204, 5207, 5214, 5228, 5234, 5245, 5249, 5256, 5262, 5275, 5278, 5305, 5303, 5315, 5321, 5348, 5358, 5369, 5369, 5372, 5385,
  5402, 5409, 5427, 5429, 5429, 5439, 5456, 5464, 5481, 5485, 5494, 5509, 5520, 5526, 5543, 5555, 5568, 5575, 5585, 5596, 5602, 5620, 5627, 5644,
  5647, 5660, 5678, 5680, 5684, 5692, 5700, 5711, 5727, 5733, 5736, 5756, 5776, 5797, 5805, 5804, 5807, 5800, 5808, 5814, 5822, 5839, 5856, 5869,
  5889, 5902, 5919, 5921, 5936, 5937, 5936, 5957, 5961, 5975, 5981, 6002, 6015, 6027, 6035, 6042, 6059, 6062, 6080, 6081, 6092, 6097, 6106, 6127,
  6129, 6198, 6227, 6231, 6243, 6249, 6262, 6255, 6279, 6304, 6315, 6326, 6330, 6334, 6361, 6358, 6359, 6379, 6381, 6389, 6388, 6404, 6404, 6443,
  6465, 6473, 6497, 6500, 6513, 6524, 6532, 6538, 6578, 6572, 6576, 6584, 6582, 6608, 6639, 6656, 6761, 6764, 6768, 6772, 6836, 6905, 6916, 6925,
  6951, 6984, 7009, 7072, 7092, 7110, 7122, 7140, 7148, 7170, 7168, 7180, 7194, 7247, 7374, 7391, 7393, 7382, 7425, 7485, 7530, 7568, 7587, 7602,
  7602, 7715, 7771, 7900, 8004, 8103, 8153, 8162, 8296, 8319, 8437, 8566, 8746, 8860, 8913, 9128, 9275, 9585, 9739, 10014, 10123, 10167, 10203, 10288,
  10323, 10398, 10544, 10721, 10883, 11044, 11157, 11442, 11515, 11787, 12070, 12269, 12468, 12484, 12619, 12883, 13008, 13264, 13317, 13549, 13859, 14049, 14175, 14360,
  14498, 14687, 14843, 14984, 15093, 15279, 15431, 15623, 15741, 15788, 15966, 16025, 16132, 16419, 16568, 16791, 16892, 17060, 17269, 17598, 17959, 18194, 18482, 18804,
  19136, 19564, 19990, 20249, 20509, 20943, 21248, 21539, 21845, 22196, 22412
]
