import type { SceneNames } from "./SceneNames.js"

/**
 * The French names of the things a scene and its catalogues hold — see SceneNames, and the build
 * scripts each catalogue says it was generated by, which keep only the English name.
 */
export const sceneNames_fr: SceneNames = {
  bodies: {
    sun: "Soleil",
    moon: "Lune",
    Venus: "Vénus",
    Saturn: "Saturne"
  },
  // Short on purpose: most of these names are Arabic-derived and are written identically in both
  // languages (Sirius, Rigel, Procyon…), so only the accented forms differ. Everything absent keeps
  // its international form, which is the form French astronomy uses too — an invented translation
  // would be worse than none.
  stars: {
    Betelgeuse: "Bételgeuse",
    Vega: "Véga",
    Altair: "Altaïr",
    Aldebaran: "Aldébaran",
    Regulus: "Régulus",
    Antares: "Antarès"
  },
  comets: {
    "halley-1910": "comète de Halley",
    "brooks-1911": "comète Brooks",
    "skjellerup-maristany-1927": "comète Skjellerup-Maristany",
    "de-kock-paraskevopoulos-1941": "comète de Kock-Paraskevopoulos",
    "southern-1947": "comète australe",
    "eclipse-1948": "comète de l'éclipse",
    "arend-roland-1957": "comète Arend-Roland",
    "mrkos-1957": "comète Mrkos",
    "seki-lines-1962": "comète Seki-Lines",
    "ikeya-seki-1965": "comète Ikeya-Seki",
    "bennett-1970": "comète Bennett",
    "white-ortiz-bolelli-1970": "comète White-Ortiz-Bolelli",
    "kohoutek-1973": "comète Kohoutek",
    "west-1976": "comète West",
    "iras-araki-alcock-1983": "comète IRAS-Araki-Alcock",
    "halley-1986": "comète de Halley",
    "hyakutake-1996": "comète Hyakutake",
    "hale-bopp-1997": "comète Hale-Bopp",
    "mcnaught-2007": "comète McNaught",
    "lovejoy-2011": "comète Lovejoy",
    "panstarrs-2013": "comète PANSTARRS",
    "neowise-2020": "comète NEOWISE",
    "tsuchinshan-atlas-2024": "comète Tsuchinshan-ATLAS"
  },
  // The constellation with its own article, as French names a nova ("nova de l'Aigle 1918").
  novae: {
    "sn-1006": "supernova de 1006",
    "sn-1054": "supernova de 1054",
    "sn-1181": "supernova de 1181",
    "sn-1572": "supernova de Tycho",
    "sn-1604": "supernova de Kepler",
    "t-crb-1866": "nova de la Couronne boréale 1866",
    "t-aur-1891": "nova du Cocher 1891",
    "gk-per-1901": "nova de Persée 1901",
    "dn-gem-1912": "nova des Gémeaux 1912",
    "v603-aql-1918": "nova de l'Aigle 1918",
    "v476-cyg-1920": "nova du Cygne 1920",
    "rr-pic-1925": "nova du Peintre 1925",
    "dq-her-1934": "nova d'Hercule 1934",
    "cp-lac-1936": "nova du Lézard 1936",
    "cp-pup-1942": "nova de la Poupe 1942",
    "t-crb-1946": "nova de la Couronne boréale 1946",
    "v446-her-1960": "nova d'Hercule 1960",
    "v533-her-1963": "nova d'Hercule 1963",
    "hr-del-1967": "nova du Dauphin 1967",
    "lv-vul-1968": "nova du Petit Renard 1968",
    "fh-ser-1970": "nova du Serpent 1970",
    "v1500-cyg-1975": "nova du Cygne 1975",
    "v842-cen-1986": "nova du Centaure 1986",
    "sn-1987a": "supernova 1987A",
    "v1974-cyg-1992": "nova du Cygne 1992",
    "v382-vel-1999": "nova des Voiles 1999",
    "v1494-aql-1999": "nova de l'Aigle 1999",
    "v4743-sgr-2002": "nova du Sagittaire 2002",
    "rs-oph-2006": "nova d'Ophiuchus 2006",
    "v1280-sco-2007": "nova du Scorpion 2007",
    "v339-del-2013": "nova du Dauphin 2013",
    "v1369-cen-2013": "nova du Centaure 2013",
    "rs-oph-2021": "nova d'Ophiuchus 2021"
  },
  satelliteClasses: {
    echo: "les ballons Echo",
    "iridium-flares": "les flashes d'Iridium",
    iss: "la Station spatiale internationale",
    "starlink-trains": "les trains de Starlink"
  },
  showers: {
    quadrantids: "Quadrantides",
    lyrids: "Lyrides d'avril",
    "eta-aquariids": "Êta Aquarides",
    "alpha-capricornids": "Alpha Capricornides",
    "southern-delta-aquariids": "Delta Aquarides du Sud",
    perseids: "Perséides",
    "southern-taurids": "Taurides du Sud",
    draconids: "Draconides d'octobre",
    orionids: "Orionides",
    "northern-taurids": "Taurides du Nord",
    leonids: "Léonides",
    geminids: "Géminides",
    ursids: "Ursides"
  },
  lightRigs: {
    "airliner": "Avion de ligne",
    "helicopter": "Hélicoptère",
    "car-headlights": "Voiture, phares allumés",
    "car-hazards": "Voiture, feux de détresse",
    "emergency-beacons": "Gyrophares de véhicule d'urgence",
    "streetlamp": "Lampadaire"
  },
  instruments: {
    eye: "Œil nu",
    "rectilinear-lens": "Appareil, modèle inconnu",
    "roamer-1-120": "Roamer 1, film 120",
    "instamatic-126": "Instamatic, film 126",
    "slr-35mm-50": "Reflex 35 mm, objectif 50 mm",
    "slr-35mm-zoom": "Reflex 35 mm, zoom 70-210 mm",
    "phone-landscape": "Téléphone, tenu couché",
    "phone-portrait": "Téléphone, tenu debout"
  },
  decorKinds: {
    building: "Bâtiment",
    tree: "Arbre",
    shrub: "Buisson",
    bridge: "Pont",
    wire: "Ligne aérienne",
    crop: "Rang de culture",
    terrace: "Restanque (terrasse)",
    mound: "Tas de pierres",
    streetlight: "Lampadaire",
    vehicle: "Véhicule",
    observer: "Observateur",
    aircraft: "Aéronef",
    entity: "Être"
  },
  // O for ouest, not W — on the scene's compass sprites and in every sentence alike.
  compassPoints: ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSO", "SO", "OSO", "O", "ONO", "NO", "NNO"],
  /**
   * The preposition depends on the ANSWER and not on the sentence: an abbreviation is read as the
   * words it stands for, so NO is "au nord-ouest" and OSO is "à l'ouest-sud-ouest". So it is the
   * leading letter that decides — est and ouest elide, nord and sud do not — which keeps ENE and OSO
   * right for the same reason E and O are.
   */
  towards: point => /^[EO]/.test(point) ? `à l'${point}` : `au ${point}`,
  starTooltip: "{name} — mag {mag}, {alt}° au-dessus de l'horizon",
  starTooltipBelow: "{name} — mag {mag}, {alt}° sous l'horizontale",
  satelliteTooltip: "{name} — satellite, mag {mag}, à {height} km d'altitude",
  trafficTooltip: {
    unnamed: "Aéronef {hex}",
    altitude: "{value} ft",
    speed: "{value} kt",
    heading: "cap {value}°",
    position: "à {distance} km, {elevation}° au-dessus de l'horizon, {bearing}",
    heard: "Entendu à {level} dB(A), parti de l'avion il y a {delay} s, {lag}° derrière lui : {character}{pitch}",
    rumble: "un grondement grave, rien au-delà de {cutoff} Hz",
    muffled: "un bruit sourd, rien au-delà de {cutoff} Hz",
    broad: "un souffle large",
    pitchHigher: ", son plus aigu de {percent} %",
    pitchLower: ", son plus grave de {percent} %",
    inaudible: "Inaudible ici : {level} dB(A) contre {ambient} dB(A) de bruit ambiant",
    soundUnknown: "Son non calculable : l'avion n'était pas encore enregistré quand il est parti",
    contrailPersistent: "Laisse une traînée qui dure : l'air est sursaturé en glace ({rhi} % par rapport à la glace)",
    contrailShort: "Laisse une traînée brève : l'air est sec par rapport à la glace ({rhi} % par rapport à la glace)",
    military: "militaire",
    restricted: "identité masquée par son propriétaire",
    candidate: "Un candidat compatible, pas une identification"
  },
  credits: "Crédits",
  notAVideo: "Ceci n'est pas une vidéo",
  isASimulation: "C'est une simulation en temps réel."
}
