/**
 * Re-derives a recording's `weatherTrack` (and its `weatherSource`) from the real meteorological
 * record for its own date, time and place — the same lookup the recorder does interactively (see
 * src/engine/weather/WeatherInference.ts), run over case files on disk.
 *
 *     npx tsx scripts/infer-case-weather.ts <path to sighting.json> [...]
 *
 * Only `weatherTrack` and `weatherSource` are written, and they are SPLICED into the file's own
 * text rather than the whole thing being re-serialized: every other key, including any this
 * project's own types don't know about, stays byte-for-byte as it was, so the diff shows the
 * weather and nothing else. (Re-serializing looked harmless and was not — these case files were
 * generated by Python, which writes `18.0` where JSON.stringify writes `18`, and normalizing that
 * buried a 3-keyframe change under 800 lines of noise.) A file the record can't answer for
 * (before 1940, no date, no place) is reported and left alone rather than half updated.
 *
 * `--dry-run` prints what each file would get without writing anything.
 */
import { readFile, writeFile } from "node:fs/promises"
import { fromSightingJson } from "../src/engine/persistence/sightingJson.js"
import type { SightingRecordingJson } from "../src/engine/persistence/sightingJson.js"
import { WeatherInference } from "../src/engine/weather/WeatherInference.js"
import { OpenMeteoWeatherProvider } from "../src/engine/weather/providers/OpenMeteoWeatherProvider.js"

/** Open-Meteo asks for no key and sets no hard rate limit, but a handful of case files in a row is
 * still a burst — one second apart is well inside anything it minds. */
const PAUSE_BETWEEN_FILES_MS = 1000

class CaseWeatherUpdater {
  private readonly inference = new WeatherInference(new OpenMeteoWeatherProvider())

  constructor(private readonly dryRun: boolean) {
  }

  async run(paths: string[]): Promise<number> {
    let failures = 0
    for (const [index, path] of paths.entries()) {
      if (index > 0) await new Promise(resolve => setTimeout(resolve, PAUSE_BETWEEN_FILES_MS))
      if (!(await this.update(path))) failures++
    }
    return failures
  }

  private async update(path: string): Promise<boolean> {
    const text = await readFile(path, "utf8")
    const json = JSON.parse(text) as SightingRecordingJson
    const sighting = fromSightingJson(json)
    const result = await this.inference.infer(sighting)
    if (result.status !== "inferred") {
      console.error(`✗ ${path}: ${result.status}`)
      return false
    }
    this.inference.applyTo(sighting, result)
    const keyframes = sighting.weatherTrack.allKeyframes
    console.log(
      `✓ ${path}: ${keyframes.length} keyframe(s) from ${result.at!.toISOString().slice(0, 16).replace("T", " ")} UTC\n` +
        keyframes.map(keyframe => `    t=${keyframe.t} ${this.describe(keyframe.weather)}`).join("\n")
    )
    if (this.dryRun) return true

    let updated = this.spliceTopLevelKey(text, "weatherTrack", sighting.weatherTrack.toJSON())
    updated = this.spliceTopLevelKey(updated, "weatherSource", sighting.weatherSource)
    // Re-parsed before writing: a splice that produced anything but the intended object is a bug
    // to fail on, never something to leave on disk.
    JSON.parse(updated)
    await writeFile(path, updated, "utf8")
    return true
  }

  /**
   * Replaces one top-level key's value in a pretty-printed (2-space) JSON document, in place,
   * appending the key just before the closing brace when it isn't there yet. Scans for the value's
   * end by brace/bracket depth, minding strings and their escapes, so it doesn't care what the
   * value contains.
   */
  private spliceTopLevelKey(text: string, key: string, value: unknown): string {
    const rendered = JSON.stringify(value, null, 2).replace(/\n/g, "\n  ")
    const marker = `\n  "${key}":`
    const at = text.indexOf(marker)
    if (at < 0) {
      const closing = text.lastIndexOf("}")
      return `${text.slice(0, closing).replace(/\s*$/, "")},\n  "${key}": ${rendered}\n${text.slice(closing)}`
    }
    let cursor = at + marker.length
    while (text[cursor] === " ") cursor++
    return text.slice(0, cursor) + rendered + text.slice(this.endOfValue(text, cursor))
  }

  private endOfValue(text: string, start: number): number {
    let depth = 0
    let inString = false
    for (let cursor = start; cursor < text.length; cursor++) {
      const character = text[cursor]
      if (inString) {
        if (character === "\\") cursor++
        else if (character === '"') inString = false
        continue
      }
      if (character === '"') inString = true
      else if (character === "{" || character === "[") depth++
      else if (character === "}" || character === "]") {
        depth--
        if (depth === 0) return cursor + 1
        // A closing brace at depth 0 is the enclosing object's: the value was a bare scalar.
        if (depth < 0) return cursor
      } else if (depth === 0 && (character === "," || character === "\n")) return cursor
    }
    return text.length
  }

  private describe(weather: { cloudCover: number; cloudBaseM?: number; precipitationType: string; windSpeed: number; storm: boolean }): string {
    const parts = [
      `cover ${(weather.cloudCover * 100).toFixed(0)}%`,
      weather.cloudBaseM === undefined ? "no deck" : `base ${weather.cloudBaseM} m`,
      `wind ${weather.windSpeed.toFixed(1)} m/s`
    ]
    if (weather.precipitationType !== "none") parts.push(weather.precipitationType)
    if (weather.storm) parts.push("storm")
    return parts.join(", ")
  }
}

const args = process.argv.slice(2)
const dryRun = args.includes("--dry-run")
const paths = args.filter(arg => !arg.startsWith("--"))
if (paths.length === 0) {
  console.error("usage: npx tsx scripts/infer-case-weather.ts [--dry-run] <sighting.json> [...]")
  process.exit(2)
}
process.exit((await new CaseWeatherUpdater(dryRun).run(paths)) > 0 ? 1 : 0)
