/**
 * Fetches and parses the compact binary star catalog assets generated by
 * scripts/build-star-catalog.ts (real HYG Database v4.1 positions/magnitudes). Kept under
 * render3d/ rather than engine/astronomy/ since it's a fetch+parse of a render-only asset, not
 * astronomy math itself.
 *
 * Binary layout (must stay in sync with build-star-catalog.ts — nothing else enforces this):
 * four Float32Array sections concatenated back-to-back, each `count` elements long, in this
 * order: ra (hours), dec (degrees), mag (apparent magnitude), ci (B-V color index).
 *
 * SORTED BRIGHTEST FIRST, and that is load-bearing rather than tidy: the renderer stops scanning at
 * the faintest magnitude the observation could record instead of walking the whole file (see
 * SceneRenderer.buildStars), so a witness's own sky costs what a witness's own sky is worth even
 * when a camera's deeper one is carried beside it.
 */
export interface StarCatalog {
  count: number
  ra: Float32Array
  dec: Float32Array
  mag: Float32Array
  ci: Float32Array
}

/**
 * How deep the tier EVERY scene loads goes — the cut scripts/build-star-catalog.ts makes, stated
 * here because it is a limit a render has to be able to admit to.
 *
 * It never mattered while every scene was drawn for an eye, which stops at 6.5 and so never reached
 * the edge of the data. An instrument does: a tripod at f/2 records past magnitude nine (see
 * LimitingMagnitude), which is why there is a second tier behind this one — fetched only by the
 * recordings that reach into it, so an ordinary sighting still pays 400 kB rather than 1.3 MB.
 */
export const STAR_CATALOG_MAGNITUDE_LIMIT = 7.5

/**
 * How deep it goes with that second tier — and where this project's star data really stops.
 *
 * Nine, because past it HYG stops being a sky and starts being a catalogue running out: its counts
 * multiply by 3.1 per magnitude up to 7, which is what a real sky does, then by 2.7 to 8, 2.0 to 9
 * and 1.3 to 10. Going deeper would mean Tycho-2 or Gaia — millions of stars, for a photograph
 * nobody has argued about yet. One that outran this is TOLD SO (see the editor's Sky line) rather
 * than quietly handed an emptier sky than it recorded.
 */
export const DEEP_STAR_CATALOG_MAGNITUDE_LIMIT = 9

/**
 * One shipped catalogue file, and how deep it goes.
 *
 * A LIST rather than two named assets, because "which catalogue" is a question about the
 * instrument: an eye needs the first entry, a tripod at f/2 needs one more, and a lens deeper than
 * anything here would need a third that does not exist yet (Tycho-2, Gaia). Adding it is then a
 * row, not a code path — and every entry past the first is a DELTA over the one before it, so no
 * star is ever downloaded twice.
 */
export interface StarCatalogTier {
  /** The faintest magnitude this tier carries. Tiers are listed brightest-cut first. */
  magnitudeLimit: number
  url: string
}

export class StarCatalogs {

  /** Cached by URL so multiple <rr0-scene> instances on one page share a single fetch/parse
   * instead of each re-downloading the catalog. */
  private static readonly cache = new Map<string, Promise<StarCatalog>>()

  static load(url: string): Promise<StarCatalog> {
    let cached = StarCatalogs.cache.get(url)
    if (!cached) {
      cached = fetch(url)
        .then(response => response.arrayBuffer())
        .then(buffer => StarCatalogs.parse(buffer))
      StarCatalogs.cache.set(url, cached)
    }
    return cached
  }

  /**
   * As much catalogue as an observation that reaches `magnitudeLimit` actually needs, as one
   * catalog — the first tier always, and each further one only while the previous still falls short
   * of what the instrument could record.
   *
   * The first tier alone is the answer for every naked-eye sighting, which is most of them, and it
   * is the reason the deep tier can exist at all: 900 kB nobody downloads unless their own optics
   * asked for it. Concatenation keeps the whole thing sorted, since each tier is fainter than the
   * one before it — an invariant the build script guarantees and the renderer's early stop relies
   * on.
   *
   * Cached under the set of URLs actually used, so switching a recording's instrument back and
   * forth does not rebuild 83 000 stars each time.
   */
  static upTo(tiers: readonly StarCatalogTier[], magnitudeLimit: number): Promise<StarCatalog> {
    const wanted = tiers.filter((_, index) => index === 0 || tiers[index - 1].magnitudeLimit < magnitudeLimit)
    if (wanted.length <= 1) return StarCatalogs.load(tiers[0].url)
    const key = wanted.map(tier => tier.url).join("\n")
    let cached = StarCatalogs.cache.get(key)
    if (!cached) {
      cached = Promise.all(wanted.map(tier => StarCatalogs.load(tier.url))).then(loaded =>
        loaded.reduce((all, tier) => StarCatalogs.concat(all, tier))
      )
      StarCatalogs.cache.set(key, cached)
    }
    return cached
  }

  private static parse(buffer: ArrayBuffer): StarCatalog {
    const count = buffer.byteLength / (4 * Float32Array.BYTES_PER_ELEMENT)
    const bytesPerSection = count * Float32Array.BYTES_PER_ELEMENT
    return {
      count,
      ra: new Float32Array(buffer, 0 * bytesPerSection, count),
      dec: new Float32Array(buffer, 1 * bytesPerSection, count),
      mag: new Float32Array(buffer, 2 * bytesPerSection, count),
      ci: new Float32Array(buffer, 3 * bytesPerSection, count)
    }
  }

  private static concat(base: StarCatalog, deeper: StarCatalog): StarCatalog {
    const join = (first: Float32Array, second: Float32Array): Float32Array => {
      const joined = new Float32Array(first.length + second.length)
      joined.set(first, 0)
      joined.set(second, first.length)
      return joined
    }
    return {
      count: base.count + deeper.count,
      ra: join(base.ra, deeper.ra),
      dec: join(base.dec, deeper.dec),
      mag: join(base.mag, deeper.mag),
      ci: join(base.ci, deeper.ci)
    }
  }
}
