/**
 * Fetches and parses the compact binary star catalog asset generated by
 * scripts/build-star-catalog.ts (real HYG Database v4.1 positions/magnitudes, filtered to
 * magnitude <= 7.5 — naked-eye visibility, since these are human eyewitness reports). Kept under
 * render3d/ rather than engine/astronomy/ since it's a fetch+parse of a render-only asset, not
 * astronomy math itself.
 *
 * Binary layout (must stay in sync with build-star-catalog.ts — nothing else enforces this):
 * four Float32Array sections concatenated back-to-back, each `count` elements long, in this
 * order: ra (hours), dec (degrees), mag (apparent magnitude), ci (B-V color index).
 */
/**
 * How deep the shipped catalogue itself goes — the cut scripts/build-star-catalog.ts makes, stated
 * here because it is a limit a RENDER has to be able to admit to.
 *
 * It never mattered while every scene was drawn for an eye, which stops at 6.5 and so never reached
 * the edge of the data. An instrument does: a tripod at f/2 records past magnitude nine (see
 * LimitingMagnitude), and everything between here and there is missing from the picture — not
 * because the photograph could not hold it, but because this project does not ship it. Going deeper
 * is a download every scene would pay for; 25 791 stars are already 400 kB.
 */
export const STAR_CATALOG_MAGNITUDE_LIMIT = 7.5

export interface StarCatalog {
  count: number
  ra: Float32Array
  dec: Float32Array
  mag: Float32Array
  ci: Float32Array
}

const cache = new Map<string, Promise<StarCatalog>>()

function parseStarCatalog(buffer: ArrayBuffer): StarCatalog {
  const count = buffer.byteLength / (4 * Float32Array.BYTES_PER_ELEMENT)
  const floatsPerSection = count
  const bytesPerSection = floatsPerSection * Float32Array.BYTES_PER_ELEMENT
  return {
    count,
    ra: new Float32Array(buffer, 0 * bytesPerSection, floatsPerSection),
    dec: new Float32Array(buffer, 1 * bytesPerSection, floatsPerSection),
    mag: new Float32Array(buffer, 2 * bytesPerSection, floatsPerSection),
    ci: new Float32Array(buffer, 3 * bytesPerSection, floatsPerSection)
  }
}

/** Module-level cached by URL so multiple <rr0-scene> instances on one page share a single
 * fetch/parse instead of each re-downloading the catalog. */
export function loadStarCatalog(url: string): Promise<StarCatalog> {
  let cached = cache.get(url)
  if (!cached) {
    cached = fetch(url)
      .then(response => response.arrayBuffer())
      .then(parseStarCatalog)
    cache.set(url, cached)
  }
  return cached
}
